sudo: false
language: node_js
node_js:
  - stable
notifications:
  email: false
cache:
  directories:
    - node_modules
install:
  - npm install
services:
  - postgresql
before_script:
  - psql -c 'create database barefoot_test;' -U postgres
script:
  - npm test
after_success:
  - npm run coverage
