version: "3.7"
services:
  db:
    image: "postgres:alpine"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis

  web: 
    environment:
      DEV_DATABASE_URL: "postgres://postgres@db:5432/postgres"
      REDIS_URL: "redis://redis:6379"
      TOKEN: "ANDELA"
      API_KEY: "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"
      baseUrl: "localhost:3000"
      FROM_EMAIL: "marveldev53@gmail.com"
      CLOUDINARY_NAME: drayzii
      CLOUDINARY_API_KEY: 684962114961327
      CLOUDINARY_API_SECRET: nd7rO_KTFnhyfkRXCS4pqzgIyjA
      GOOGLE_CLIENT_ID: 521248916925-ttu587qlg15lu551phfh3th78agds3dv.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: YqdoMG2xstMCN_qUB6bHuQvF
      FB_CLIENT_ID: 2953236191359414
      FB_CLIENT_SECRET: 1b018140636e8cb098de1dfe22178ad1
    build: .
    depends_on:
      - db
      - redis
    ports: 
      [3000:3000]
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    
